// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mCO-L4u_yJBfJk_BGMonseJAc9bNuZA',
    appId: '1:664419252809:web:2a0eecdd2a492957ae1d98',
    messagingSenderId: '664419252809',
    projectId: 'flutter-firebase-8006c',
    authDomain: 'flutter-firebase-8006c.firebaseapp.com',
    storageBucket: 'flutter-firebase-8006c.firebasestorage.app',
    measurementId: 'G-MVBV6H0328',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mCO-L4u_yJBfJk_BGMonseJAc9bNuZA',
    appId: '1:664419252809:web:857167c70035682aae1d98',
    messagingSenderId: '664419252809',
    projectId: 'flutter-firebase-8006c',
    authDomain: 'flutter-firebase-8006c.firebaseapp.com',
    storageBucket: 'flutter-firebase-8006c.firebasestorage.app',
    measurementId: 'G-CFYYZGM68L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JHzwHW04ZLOqZ87D8Hx8nk1T7BLyc5A',
    appId: '1:664419252809:ios:8a78f36f17a11820ae1d98',
    messagingSenderId: '664419252809',
    projectId: 'flutter-firebase-8006c',
    storageBucket: 'flutter-firebase-8006c.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JHzwHW04ZLOqZ87D8Hx8nk1T7BLyc5A',
    appId: '1:664419252809:ios:8a78f36f17a11820ae1d98',
    messagingSenderId: '664419252809',
    projectId: 'flutter-firebase-8006c',
    storageBucket: 'flutter-firebase-8006c.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK1ywFyImhcshVLulAIlnDS1asv9crZYE',
    appId: '1:664419252809:android:47a1c4103535255bae1d98',
    messagingSenderId: '664419252809',
    projectId: 'flutter-firebase-8006c',
    storageBucket: 'flutter-firebase-8006c.firebasestorage.app',
  );

}